-- Run this in your Supabase SQL Editor to set up the Supply Chain Management System

create table if not exists orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text not null,
  customer_address text not null,
  customer_phone text, -- Optional contact
  distance_km numeric, -- Manual entry or calculated
  delivery_fee numeric default 0,
  total_amount numeric default 0,
  status text default 'Pending', -- Pending, Processing, Out for Delivery, Delivered, Cancelled
  payment_status text default 'Pending', -- Pending, Paid
  payment_method text, -- UPI, Cash, Bank Transfer
  salesperson text, -- Darshan, Suraj, Sushant
  delivery_boy text, -- Assigned delivery person
  delivery_date date, -- Scheduled delivery date
  notes text
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade not null,
  product_type text not null, -- 'Plastic Box (250g)', 'Cardboard Box (1kg)'
  quantity integer not null default 1,
  price_per_unit numeric default 0
);

-- Enable Row Level Security (RLS) is generally good practice, 
-- but for a simple internal tool we can start with open access or basic auth.
-- ensure you have RLS disabled or proper policies if you enable it.
