
-- Create a new table for tracking supplier (Gade) transactions
CREATE TABLE IF NOT EXISTS supplier_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('Order', 'Payment')), -- 'Order' means we took stock, 'Payment' means we paid him
    description TEXT,
    quantity_kg NUMERIC DEFAULT 0, -- For orders
    amount NUMERIC DEFAULT 0, -- For both orders (cost) and payments
    notes TEXT
);

-- Policy to allow all access (since we are currently using anon key for everything in this prototype)
CREATE POLICY "Enable all access for supplier_transactions" ON supplier_transactions FOR ALL USING (true) WITH CHECK (true);
