-- ENTIRE DATABASE SCHEMA FOR NATIVE BERRY
-- Run this in Supabase SQL Editor to set up a fresh project.

-- 1. ORDERS TABLE
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    customer_name TEXT NOT NULL,
    customer_address TEXT NOT NULL,
    customer_phone TEXT,
    distance_km NUMERIC,
    payment_status TEXT CHECK (payment_status IN ('Pending', 'Paid')),
    payment_method TEXT,
    salesperson TEXT,
    delivery_date DATE,
    notes TEXT,
    status TEXT DEFAULT 'Pending',
    delivery_notes TEXT,
    total_amount NUMERIC(10, 2) DEFAULT 0,
    delivery_boy TEXT,
    bike_used BOOLEAN DEFAULT FALSE,
    travel_charge NUMERIC DEFAULT 0
);

-- 2. ORDER ITEMS TABLE
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    product_type TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    weight_kg NUMERIC NOT NULL,
    unit_price NUMERIC(10, 2) NOT NULL
);

-- 3. EXPENSES TABLE
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    description TEXT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    category TEXT DEFAULT 'General',
    date TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 4. VISITOR LOGS TABLE
CREATE TABLE IF NOT EXISTS visitor_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    ip_address TEXT,
    city TEXT,
    region TEXT,
    country TEXT,
    user_agent TEXT,
    isp TEXT
);

-- OPTIONAL: Row Level Security (RLS) Setup
-- Since the app currently handles auth on the client-side (AdminLogin.tsx), 
-- we need to ensure the 'anon' (public) key has access to these tables.
-- It is recommended to enable RLS and strictly define policies in a production environment.

-- Enable RLS
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE visitor_logs ENABLE ROW LEVEL SECURITY;

-- Create Policies (Allowing full access for now since Auth is custom/dummy)
-- WARNING: This allows anyone with your Anon Key to Read/Write these tables. 
-- Ideally, you should integrate Supabase Auth.

CREATE POLICY "Enable all access for orders" ON orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for order_items" ON order_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for expenses" ON expenses FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for visitor_logs" ON visitor_logs FOR ALL USING (true) WITH CHECK (true);
