-- UPDATED SCHEMA: BUSINESS FINANCIALS
-- Run this in Supabase SQL Editor to upgrade your system to track PROFITS

-- 1. Orders Table: Adding Financial Fields
alter table orders 
add column if not exists total_amount numeric default 0,
add column if not exists total_cost numeric default 0,
add column if not exists estimated_profit numeric default 0;

-- 2. Order Items: Adding Pricing per Item
alter table order_items
add column if not exists unit_price numeric default 0,
add column if not exists unit_cost numeric default 0;

-- 3. Pre-defined Prices Table (Optional but good for management)
-- This allows you to set today's Buying/Selling rates
create table if not exists daily_rates (
  id bigint generated by default as identity primary key,
  date date default current_date unique,
  buying_price_250g numeric default 60, -- What you pay farmer
  selling_price_250g numeric default 100, -- What you charge customer
  buying_price_1kg numeric default 200,
  selling_price_1kg numeric default 350
);

-- Insert default rates for today if not exists
insert into daily_rates (date, buying_price_250g, selling_price_250g, buying_price_1kg, selling_price_1kg)
values (current_date, 60, 100, 200, 350)
on conflict do nothing;
