-- MASTER SUPPLY CHAIN SCHEMA
-- Run this ENTIRE script in your Supabase SQL Editor to initialize the Supply Chain System.

-- 1. Create Orders Table
create table if not exists orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text not null,
  customer_address text not null,
  customer_phone text,
  distance_km numeric,
  delivery_fee numeric default 0,
  status text default 'Pending', -- Pending, Out for Delivery, Delivered, Cancelled
  payment_status text default 'Pending', -- Pending, Paid
  payment_method text,
  salesperson text,
  delivery_boy text,
  delivery_date date,
  notes text,
  delivery_notes text,
  total_amount numeric default 0,      -- Financial: Total Bill
  total_cost numeric default 0,        -- Financial: Cost of goods (Optional)
  estimated_profit numeric default 0,   -- Financial: Profit (Optional)
  payment_received_by text            -- To track who collected the cash (Sushant, Suraj, Darshan, etc.)
);

-- 2. Create Order Items Table
create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade not null,
  product_type text not null, -- 'Plastic Box (250g)' or 'Cardboard Box (1kg)'
  quantity integer not null default 1,
  weight_kg numeric not null default 0,
  unit_price numeric default 0, -- Price at time of sale
  unit_cost numeric default 0
);

-- 3. Create Daily Rates Table (For defaults)
create table if not exists daily_rates (
  id bigint generated by default as identity primary key,
  date date default current_date unique,
  buying_price_250g numeric default 60,
  selling_price_250g numeric default 100,
  buying_price_1kg numeric default 200,
  selling_price_1kg numeric default 350
);

-- 4. Create Visitor Logs (If not exists from previous work)
create table if not exists visitor_logs (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    visitor_name text,
    location text,
    notes text
);

-- 5. Create View for Farmer Requirements
create or replace view daily_product_requirements as
select 
  o.delivery_date,
  oi.product_type,
  sum(oi.quantity) as total_units,
  sum(oi.weight_kg) as total_weight_kg
from orders o
join order_items oi on o.id = oi.order_id
where o.status not in ('Cancelled', 'Delivered')
group by o.delivery_date, oi.product_type
order by o.delivery_date;

-- 6. Enable Row Level Security (Good practice, but allowing public access for this MVP)
alter table orders enable row level security;
alter table order_items enable row level security;
alter table daily_rates enable row level security;

-- 7. Create Policies (Allowing anon public access for simplicity in this dev phase)
create policy "Allow public access orders" on orders for all using (true) with check (true);
create policy "Allow public access items" on order_items for all using (true) with check (true);
create policy "Allow public access rates" on daily_rates for all using (true) with check (true);
