-- Run this key in your Supabase SQL Editor to update the database schema

-- 1. Create Expenses Table
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    description TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    category TEXT DEFAULT 'General',
    date TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 2. Add columns to Orders table for delivery details
ALTER TABLE orders 
ADD COLUMN IF NOT EXISTS bike_used BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS travel_charge NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS delivery_notes TEXT;

-- 3. (Optional) Policies if RLS is enabled
-- ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Enable all access for authenticated users" ON expenses FOR ALL USING (auth.role() = 'authenticated');
