-- COMPLETE SUPPLY CHAIN SCHEMA
-- Run this in Supabase SQL Editor

-- 1. Orders Table
create table if not exists orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text not null,
  customer_address text not null,
  customer_phone text, 
  distance_km numeric, 
  delivery_fee numeric default 0,
  
  -- Order Status
  status text default 'Pending', -- 'Pending', 'Confirmed', 'Processing', 'Out for Delivery', 'Delivered', 'Cancelled'
  
  -- Payment
  payment_status text default 'Pending', -- 'Pending', 'Paid'
  payment_method text, -- 'Cash', 'UPI', 'Bank Transfer'
  
  -- Logistics
  salesperson text, -- 'Darshan', 'Suraj', 'Sushant'
  delivery_boy text, -- Assigned Driver
  delivery_date date, -- Planned Delivery Date
  
  notes text,
  delivery_proof_url text -- For uploading photo of delivery (optional future)
);

-- 2. Order Items (Products)
create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade not null,
  product_type text not null, -- 'Plastic Box (250g)', 'Cardboard Box (1kg)'
  quantity integer not null default 1,
  weight_kg numeric not null default 0
);

-- 3. Visitor Logs (if not already present for the other tracker)
create table if not exists visitor_logs (
  id bigint generated by default as identity primary key,
  ip_address text,
  city text,
  region text,
  country text,
  user_agent text,
  isp text,
  visited_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Create a view for Farmer Data (Daily Totals)
create or replace view daily_product_requirements as
select 
  o.delivery_date,
  oi.product_type,
  sum(oi.quantity) as total_units,
  sum(oi.weight_kg) as total_weight_kg
from orders o
join order_items oi on o.id = oi.order_id
where o.status not in ('Cancelled', 'Delivered')
group by o.delivery_date, oi.product_type
order by o.delivery_date;
